import type { Metadata } from "next";
import { Scheherazade_New, Noto_Naskh_Arabic } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const scheherazade = Scheherazade_New({
  weight: ["400", "700"],
  subsets: ["arabic"],
  variable: "--font-quran",
  display: "swap",
});

const notoNaskhArabic = Noto_Naskh_Arabic({
  weight: ["400", "700"],
  subsets: ["arabic"],
  variable: "--font-quran2",
  display: "swap",
});

const uthmanic = localFont({
  src: "../public/font/uthmanic/KFGQPC HAFS Uthmanic Script.woff2",
  variable: "--font-numbers",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${scheherazade.variable} ${uthmanic.variable} ${notoNaskhArabic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
